# Generated by Django 4.0 on 2022-01-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
    ]
